-- SQL SCRIPT TO CREATE THE TABLES
-- SCHEMA CREATION
CREATE SCHEMA BD_UNB;

-- STUDENT
CREATE TABLE BD_UNB.STUDENT
(
    ID              SERIAL,
    COD_MAT         INT                 NOT NULL    UNIQUE,
    SEX             VARCHAR(50)         NOT NULL, 
    AGE             INT, 
    QUOTA           VARCHAR(100),
    SCHOOL_TYPE     VARCHAR(100),
    RACE            VARCHAR(100),
    LOCAL           INT, 
    COURSE          VARCHAR(100),
    YEAR_IN         INT, 
    YEAR_END        INT, 
PRIMARY KEY(ID));

-- SUBJECT
CREATE TABLE BD_UNB.SUBJECT
(
    ID              SERIAL,
    CODE            INT                 NOT NULL    UNIQUE,
    NAME            VARCHAR(100)        NOT NULL, 
    -- CREDITS         INT                 NOT NULL,
PRIMARY KEY(ID)); 

-- RELANTIONSHIP BETWEEN STUDENT AND SUBJECT
CREATE TABLE BD_UNB.STUDENT_SUBJECT
(
    CODE_STU        INT,
    CODE_SUB        INT, 
    SEMESTER        INT             NOT NULL,
    YEAR            INT             NOT NULL,
    GRADE           VARCHAR(10),
PRIMARY KEY (CODE_STU, CODE_SUB), 
FOREIGN KEY (CODE_STU) REFERENCES BD_UNB.STUDENT (COD_MAT)
    ON DELETE CASCADE, 
FOREIGN KEY (CODE_SUB) REFERENCES BD_UNB.SUBJECT (CODE)
    ON DELETE CASCADE
); 
